package beans;

public enum Simptom {

	CURENJE_IZ_NOSA,
	BOL_U_GRLU,
	GLAVOBOLJA,
	KIJANJE,
	KASALJ,
	TEMPERATURA_VECA_OD_38,
	DRHTAVICA,
	BOL_KOJI_SE_SIRI_DO_USIJU,
	TEMPERATURA_OD_40_DO_41,
	GUBITAK_APETITA,
	UMOR,
	ZUTI_SEKRET_IZ_NOSA,
	OTICANJE_OKO_OCIJU,
	PACIJENT_BOLOVAO_OD_PREHLADE_ILI_GROZNICE_U_POSLEDNJIH_60_DANA,
	U_POSLEDNJIH_6_MESECI_ZABELEZENO_BAR_10_SLUCAJEVA_U_KOJEM_JE_PACIJENT_IMAO_VISOK_PRITISAK,
	CESTO_URINIRANJE,
	GUBITAK_TELESNE_TEZINE,
	ZAMOR,
	MUCNINA_I_POVRACANJE,
	NOCTURIA,
	OTOCI_NOGU_I_ZGLOBOVA,
	GUSENJE,
	BOL_U_GRUDIMA,
	PACIJENT_BOLUJE_OD_HIPERTENZIJE_VISE_OD_6_MESECI,
	PACIJENT_BOLUJE_OD_DIJABETESA,
	OPORAVLJA_SE_OD_OPERACIJE,
	DIJAREJA,
	U_POSLEDNJIH_14_DANA_DIJAGNOSTIKOVANA_BOLEST_KOJA_KAO_SIMPTOM_IMA_POVISENU_TELESNU_TEMPERATURU,
	U_POSLEDNJIH_21_DANA_DIJAGNOSTIKOVANA_BOLEST_ZA_KOJU_JE_PRIMAO_ANTIBIOTIKE;
	
}
